// src/app/layout.jsx
import Head from 'next/head';
import './globals.css';

export const metadata = {
  title: 'Luminova - Event Planning Simplified',
  description: 'Generated by Luminova',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Link to favicon */}
        <link
          rel="icon"
          href="/Assets/images/letter-l-logo-icon-design-with-swoosh-and-creative-curved-cut-shape-vector-removebg-preview.png"
          type="image/png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/Assets/images/letter-l-logo-icon-design-with-swoosh-and-creative-curved-cut-shape-vector-removebg-preview.png"
        />
        <link
          rel="shortcut icon"
          href="/Assets/images/letter-l-logo-icon-design-with-swoosh-and-creative-curved-cut-shape-vector-removebg-preview.png"
          type="image/png"
        />
      </Head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
